<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OracleColumnMapping.cs" />
    <Compile Remove="OracleEnums.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net6.0\" />
  </ItemGroup>

</Project>
